### ISSUE TITLE
Playing a game multiple times results in multiple history mentions

### ISSUE THREAD

**Issue by VFDan** [LeShaps/FPL-History#1]
![image](https://user-images.githubusercontent.com/44413950/113740184-7bd63f80-96ce-11eb-8193-71d188748bc5.png)

**Comment by LeShaps** [comment]
Thanks for the report!
I plan to allow a configuration to have a more Steam-like history, I'll keep you in touch!

**Comment by LeShaps** [comment]
Resolved in 1.2.0
